### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by ritajeong** [strapi/strapi-template-catalog#4]
I tried it with npx, but there is still an error.
```
$ npx create-strapi-app my-app-name --template https://github.com/strapi/strapi-template-catalog
npx: installed 104 in 10.156s
? Choose your installation type (Use arrow keys)
? Choose your installation type Quickstart (recommended)
Creating a quickstart project.
Creating a new Strapi application at C:\GitHub\strapi\example\my-app-name.
Creating files.
Error: ⛔️ Template installation failed: Command failed: C:\WINDOWS\system32\cmd.exe /q /s /c "npm view https://github.com/strapi/strapi-template-catalog name version --silent"


    at createProject (C:\Users\User\AppData\Roaming\npm-cache\_npx\95244\node_modules\create-strapi-app\node_modules\@strapi\generate-new\lib\create-project.js:82:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async createQuickStartProject (C:\Users\User\AppData\Roaming\npm-cache\_npx\95244\node_modules\create-strapi-app\node_modules\@strapi\generate-new\lib\create-quickstart-project.js:23:3)

```
Windows 10
git bash
npm 6.14.14

**Comment by balichowdry** [comment]
I have same issue, any help?
